// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmS57glKz-LRDNNHxxRxRiseypKNLfjR4',
    appId: '1:995302022193:web:bdb8a4d702e9608678c910',
    messagingSenderId: '995302022193',
    projectId: 'filmscollection-9ac5a',
    authDomain: 'filmscollection-9ac5a.firebaseapp.com',
    databaseURL: 'https://filmscollection-9ac5a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'filmscollection-9ac5a.appspot.com',
    measurementId: 'G-S4JLDKNLEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4uWqgpfHrpOatx2vraiDqvTFslOXYKIQ',
    appId: '1:995302022193:android:f9e5d0d6ea898b9578c910',
    messagingSenderId: '995302022193',
    projectId: 'filmscollection-9ac5a',
    databaseURL: 'https://filmscollection-9ac5a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'filmscollection-9ac5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEyRA8jSGrobTYbe4200XeaBGFzYrr5BU',
    appId: '1:995302022193:ios:b9a616a947c2845878c910',
    messagingSenderId: '995302022193',
    projectId: 'filmscollection-9ac5a',
    databaseURL: 'https://filmscollection-9ac5a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'filmscollection-9ac5a.appspot.com',
    iosBundleId: 'com.example.filmsCollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEyRA8jSGrobTYbe4200XeaBGFzYrr5BU',
    appId: '1:995302022193:ios:b9a616a947c2845878c910',
    messagingSenderId: '995302022193',
    projectId: 'filmscollection-9ac5a',
    databaseURL: 'https://filmscollection-9ac5a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'filmscollection-9ac5a.appspot.com',
    iosBundleId: 'com.example.filmsCollection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmS57glKz-LRDNNHxxRxRiseypKNLfjR4',
    appId: '1:995302022193:web:477911eb64d27d4d78c910',
    messagingSenderId: '995302022193',
    projectId: 'filmscollection-9ac5a',
    authDomain: 'filmscollection-9ac5a.firebaseapp.com',
    databaseURL: 'https://filmscollection-9ac5a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'filmscollection-9ac5a.appspot.com',
    measurementId: 'G-F29CEWBNFH',
  );
}
